### Section 4.3. Functions to Create Arrays 

In [7]:
# create array
from numpy import array

# create array
l = [1.0, 2.0, 3.0]
a = array(l)

# display array
print(a)

# display array shape
print(a.shape)

# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [9]:
# create empty array (random numbers will be given)
from numpy import empty
a = empty([3,3])
print(a)

[[1.72723371e-077 1.29074041e-231 2.25462053e-314]
 [2.25666864e-314 2.25453616e-314 2.25448815e-314]
 [2.25516717e-314 2.25448054e-314 2.25453456e-314]]
